# Generated by Django 3.2.4 on 2025-05-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerstock',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='retailer_qr/'),
        ),
    ]
