# Generated by Django 3.2.4 on 2025-05-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_retailerstock_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailerstock',
            name='qr_image',
        ),
    ]
