# Generated by Django 3.2.4 on 2025-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_block_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerstock',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
