# Generated by Django 3.2.4 on 2025-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_retailerstock_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='chain_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Transactions'), ('DISTRIBUTOR', 'Distributor Transactions')], default='CUSTOMER', max_length=20),
        ),
    ]
