# Generated by Django 3.2.4 on 2025-05-08 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_block_chain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chain_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Transaction'), ('DISTRIBUTOR', 'Distributor Transaction')], default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
