# Generated by Django 3.2.4 on 2025-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250508_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorstock',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
