# Generated by Django 3.2.4 on 2025-05-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_distributorstock_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='distributor',
        ),
        migrations.AddField(
            model_name='transaction',
            name='manu_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.manufacturerproduct'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.retailerstock'),
        ),
    ]
