# Generated by Django 5.2.6 on 2025-09-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250508_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='user_upi_qr_codes/'),
        ),
    ]
